name: Dealings
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  firebase_core:
  firebase_auth:
  firebase_messaging:
  google_maps_flutter:
  http:
  shared_preferences:
  avatar_glow:

  image_picker:
  infinite_scroll:
  calendar_date_picker2:
  intl:
  dartz:
  flutter_otp_text_field:
  cached_network_image:
  rating_dialog:
  flutter_paypal_checkout:
  flutter_native_splash:
  flutter_neumorphic:
  pedometer:
  percent_indicator:
  lottie:
  fl_chart:
  url_launcher:
  fancy_drawer:
  animated_bottom_navigation_bar:
  flutter_link_previewer:
  syncfusion_flutter_barcodes: ^22.2.10
  qr_code_dart_scan:
  flutter_barcode_scanner:
  qr_code_scanner:
  printing:
  pdf:
  flutter_ringtone_player:
  googleapis:
  googleapis_auth:
  flutter_speed_dial:
  bottom_bar:
  expansion_tile_card:
  supabase: ^0.3.6
  supabase_flutter: ^0.3.3





  cupertino_icons: ^1.0.2
  simple_animated_icon:

  # flutter_native_splash:
  #   android: true
  #  ios: true
  #  android_gravity: center
  #  color: "#42a5f5"
  #  image: assets/images/smartFull.png
dev_dependencies:
  flutter_test:
    sdk: flutter
    #  flutter_native_splash: ^2.2.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/LogoApp/dealingsFull.png"



  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/LogoApp/
    - assets/images/onboarding/
    - assets/images/Bar/
    - assets/images/More/
    - assets/font/
    - assets/
    - assets/lottie/


  fonts:
    - family: Lato
      fonts:
        - asset: assets/font/Lato-Regular.ttf

    - family: NotoKufiArabic
      fonts:
        - asset: assets/font/NotoKufiArabic-Regular.ttf


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
